<?php

/**
 * Implements hook_menu()
 */
function page_api_menu() {
  $items = array();
  $items['page_api/%/%'] = array(
    'title' => 'Page JSON Service',
    'description' => 'Provide Page JSON Service',
    'page callback' => 'page_api_output',
    'access callback' => TRUE,
    'page arguments' => array(1, 2),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter()
 */
function page_api_form_system_site_information_settings_alter(&$form, &$form_state, $form_id) {
  $form['site_api_key'] = array(
    '#type' => 'fieldset',
    '#title' => t("Site API"),
  );
  $form['site_api_key']['siteapikey'] = array(
    '#type' => 'textfield',
    '#title' => t("Site API Key"),
    '#attributes' => array('placeholder' => t('No API Key yet')),
    '#required' => TRUE,
    '#default_value' => variable_get('siteapikey', ''),
  );
  $form['#submit'] = array_merge($form['#submit'], array('page_api_form_system_site_information_settings_submit'));
  if (variable_get('siteapikey', '') != '') {
    $form['actions']['submit']['#value'] = t("Update Configuration");
  }
  return $form;
}

/**
 * Implements hook_form_FROM_ID_submit()
 */
function page_api_form_system_site_information_settings_submit($form, &$form_state) {
  variable_set('siteapikey', $form_state['values']['siteapikey']);
  drupal_set_message(t("Site API Key has been saved with @siteapikey", array("@siteapikey" => $form_state['values']['siteapikey'])));
}

function page_api_output($site_api, $nid) {
  $node = node_load($nid);
  print drupal_json_output($node);
}